In [28]:
import torch
import numpy as np

In [6]:
# unlike python array, pytorch use tensor
x = torch.empty(2, 3, 4)
x

tensor([[[0.0000e+00, 4.2005e-05, 1.8788e+31, 1.7220e+22],
         [2.1715e-18, 8.4708e-07, 5.3241e+22, 3.3424e+21],
         [3.2772e-09, 2.5963e+20, 6.8243e-07, 2.0432e+20]],

        [[1.0385e+21, 1.6519e-07, 2.6516e-09, 4.1023e-08],
         [2.1707e-18, 1.6678e+19, 7.0976e+22, 2.1715e-18],
         [4.2330e+21, 1.6534e+19, 1.1625e+27, 1.4580e-19]]])

In [7]:
x = torch.rand(2, 2)
x

tensor([[0.7724, 0.8213],
        [0.8501, 0.6872]])

In [10]:
# same thing apply to zeros and defined the data type
x = torch.ones(4, 4, dtype=torch.int)
x

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [11]:
x.dtype

torch.int32

In [13]:
x.size()

torch.Size([4, 4])

In [14]:
x = torch.tensor([12, 23, 34, 45, 5.6])
x

tensor([12.0000, 23.0000, 34.0000, 45.0000,  5.6000])

In [15]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.9843, 0.9356],
        [0.3848, 0.3790]])
tensor([[0.0623, 0.0549],
        [0.5158, 0.7420]])


In [16]:
z = x + y
z

tensor([[1.0466, 0.9905],
        [0.9006, 1.1210]])

In [17]:
# inplace adding (add and replace the x tensor with new values)
x.add_(y)
x

tensor([[1.0466, 0.9905],
        [0.9006, 1.1210]])

In [21]:
x = torch.rand(5, 3)
print(x[0, :])  # we can also do slicing like numpy array

tensor([0.1774, 0.6095, 0.4386])


In [24]:
print(x[0, 0].item())  # get the value, not the tensor

0.17735475301742554


In [25]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)

tensor([[0.4397, 0.5717, 0.5114, 0.2410],
        [0.4805, 0.4141, 0.9239, 0.4936],
        [0.7695, 0.0889, 0.3538, 0.2388],
        [0.3783, 0.0665, 0.0972, 0.4083]])
tensor([0.4397, 0.5717, 0.5114, 0.2410, 0.4805, 0.4141, 0.9239, 0.4936, 0.7695,
        0.0889, 0.3538, 0.2388, 0.3783, 0.0665, 0.0972, 0.4083])


In [27]:
y = x.view(
    -1, 8
)  # we can reshape the tensor, just enter 1 dimension and other dimension -1 pytorch will calculate it automatically
y

tensor([[0.4397, 0.5717, 0.5114, 0.2410, 0.4805, 0.4141, 0.9239, 0.4936],
        [0.7695, 0.0889, 0.3538, 0.2388, 0.3783, 0.0665, 0.0972, 0.4083]])

In [30]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()  # convert from tensor to numpy array
print(type(b))

<class 'numpy.ndarray'>


In [33]:
a.add_(1)
print(a)
print(b)  # a and b both point to the same memory on cpu

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [34]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    z = x

cuda


In [36]:
x = torch.ones(
    5, requires_grad=True
)  # remind torch that we will use these for gradient later
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
